import { SceneObjectType } from '@/store/SceneContext';

export interface ObjectTemplate {
  type: SceneObjectType;
  label: string;
  icon: string;
  width: number;
  height: number;
  color: string;
  category: string;
}

export const objectLibrary: Record<string, ObjectTemplate[]> = {
  'Bodies': [
    { type: 'body-outline', label: 'Body Outline', icon: '🧍', width: 60, height: 120, color: '#ef4444', category: 'Bodies' },
    { type: 'body-standing', label: 'Standing', icon: '🧑', width: 40, height: 80, color: '#ef4444', category: 'Bodies' },
    { type: 'body-prone', label: 'Prone', icon: '🏊', width: 120, height: 40, color: '#ef4444', category: 'Bodies' },
    { type: 'body-seated', label: 'Seated', icon: '🧘', width: 50, height: 60, color: '#ef4444', category: 'Bodies' },
    { type: 'body-fetal', label: 'Fetal Position', icon: '🫃', width: 60, height: 50, color: '#ef4444', category: 'Bodies' },
  ],
  'Weapons': [
    { type: 'knife', label: 'Knife', icon: '🔪', width: 40, height: 15, color: '#94a3b8', category: 'Weapons' },
    { type: 'gun', label: 'Handgun', icon: '🔫', width: 50, height: 30, color: '#475569', category: 'Weapons' },
    { type: 'rifle', label: 'Rifle', icon: '🎯', width: 100, height: 20, color: '#374151', category: 'Weapons' },
    { type: 'shotgun', label: 'Shotgun', icon: '💥', width: 90, height: 18, color: '#44403c', category: 'Weapons' },
    { type: 'bat', label: 'Bat/Club', icon: '🏏', width: 60, height: 12, color: '#78716c', category: 'Weapons' },
    { type: 'crowbar', label: 'Crowbar', icon: '🪝', width: 50, height: 10, color: '#475569', category: 'Weapons' },
    { type: 'rope', label: 'Rope/Cord', icon: '🪢', width: 80, height: 8, color: '#a8a29e', category: 'Weapons' },
    { type: 'bullet-casing', label: 'Casing', icon: '⊙', width: 10, height: 10, color: '#d97706', category: 'Weapons' },
    { type: 'bullet-hole', label: 'Bullet Hole', icon: '⊗', width: 12, height: 12, color: '#1e293b', category: 'Weapons' },
  ],
  'Evidence': [
    { type: 'evidence-marker', label: 'Marker', icon: '🔶', width: 30, height: 30, color: '#eab308', category: 'Evidence' },
    { type: 'blood-stain', label: 'Blood Stain', icon: '🩸', width: 40, height: 30, color: '#dc2626', category: 'Evidence' },
    { type: 'footprint', label: 'Footprint', icon: '👣', width: 25, height: 50, color: '#78716c', category: 'Evidence' },
    { type: 'tire-mark', label: 'Tire Mark', icon: '〰️', width: 120, height: 20, color: '#1c1917', category: 'Evidence' },
    { type: 'fingerprint', label: 'Fingerprint', icon: '🖐️', width: 20, height: 25, color: '#a3a3a3', category: 'Evidence' },
    { type: 'hair-fiber', label: 'Hair/Fiber', icon: '🧬', width: 15, height: 15, color: '#92400e', category: 'Evidence' },
    { type: 'clothing', label: 'Clothing', icon: '👕', width: 40, height: 40, color: '#6366f1', category: 'Evidence' },
    { type: 'document-evidence', label: 'Document', icon: '📄', width: 30, height: 40, color: '#f5f5f4', category: 'Evidence' },
    { type: 'drug-paraphernalia', label: 'Drugs/Para.', icon: '💊', width: 20, height: 20, color: '#f97316', category: 'Evidence' },
    { type: 'glass-fragment', label: 'Glass', icon: '💎', width: 25, height: 20, color: '#67e8f9', category: 'Evidence' },
    { type: 'shell-casing', label: 'Shell Casing', icon: '🔩', width: 12, height: 12, color: '#ca8a04', category: 'Evidence' },
    { type: 'dna-sample', label: 'DNA Sample', icon: '🧪', width: 15, height: 15, color: '#22c55e', category: 'Evidence' },
    { type: 'phone', label: 'Phone', icon: '📱', width: 20, height: 35, color: '#1e293b', category: 'Evidence' },
    { type: 'camera', label: 'Camera', icon: '📷', width: 30, height: 25, color: '#334155', category: 'Evidence' },
    { type: 'id-card', label: 'ID Card', icon: '🪪', width: 35, height: 22, color: '#e2e8f0', category: 'Evidence' },
    { type: 'bag', label: 'Bag', icon: '👜', width: 35, height: 30, color: '#78716c', category: 'Evidence' },
    { type: 'wallet', label: 'Wallet', icon: '👛', width: 20, height: 15, color: '#78716c', category: 'Evidence' },
    { type: 'keys', label: 'Keys', icon: '🔑', width: 15, height: 15, color: '#d4d4d8', category: 'Evidence' },
    { type: 'cigarette-butt', label: 'Cigarette Butt', icon: '🚬', width: 10, height: 10, color: '#a8a29e', category: 'Evidence' },
    { type: 'weapon-sheath', label: 'Sheath/Holster', icon: '🔰', width: 25, height: 15, color: '#57534e', category: 'Evidence' },
  ],
  'Furniture': [
    { type: 'bed', label: 'Bed', icon: '🛏️', width: 120, height: 80, color: '#7c3aed', category: 'Furniture' },
    { type: 'table', label: 'Table', icon: '🪑', width: 80, height: 60, color: '#92400e', category: 'Furniture' },
    { type: 'chair', label: 'Chair', icon: '💺', width: 40, height: 40, color: '#92400e', category: 'Furniture' },
    { type: 'sofa', label: 'Sofa', icon: '🛋️', width: 120, height: 50, color: '#6d28d9', category: 'Furniture' },
    { type: 'cabinet', label: 'Cabinet', icon: '🗄️', width: 60, height: 30, color: '#78716c', category: 'Furniture' },
    { type: 'nightstand', label: 'Nightstand', icon: '🗃️', width: 35, height: 35, color: '#78716c', category: 'Furniture' },
    { type: 'dresser', label: 'Dresser', icon: '🪟', width: 80, height: 40, color: '#92400e', category: 'Furniture' },
    { type: 'bookcase', label: 'Bookcase', icon: '📚', width: 80, height: 30, color: '#78716c', category: 'Furniture' },
    { type: 'rug', label: 'Rug/Carpet', icon: '🟫', width: 100, height: 70, color: '#a16207', category: 'Furniture' },
    { type: 'mirror', label: 'Mirror', icon: '🪞', width: 40, height: 8, color: '#bfdbfe', category: 'Furniture' },
    { type: 'tv-stand', label: 'TV Stand', icon: '📺', width: 100, height: 30, color: '#1e293b', category: 'Furniture' },
  ],
  'Structures': [
    { type: 'door', label: 'Door', icon: '🚪', width: 60, height: 10, color: '#92400e', category: 'Structures' },
    { type: 'sliding-door', label: 'Sliding Door', icon: '↔️', width: 80, height: 10, color: '#94a3b8', category: 'Structures' },
    { type: 'garage-door', label: 'Garage Door', icon: '🏠', width: 120, height: 12, color: '#d1d5db', category: 'Structures' },
    { type: 'archway', label: 'Archway', icon: '🌉', width: 60, height: 10, color: '#a8a29e', category: 'Structures' },
    { type: 'window', label: 'Window', icon: '🪟', width: 60, height: 8, color: '#38bdf8', category: 'Structures' },
    { type: 'wall', label: 'Wall', icon: '▬', width: 120, height: 10, color: '#334155', category: 'Structures' },
    { type: 'stairs', label: 'Stairs', icon: '🪜', width: 60, height: 80, color: '#78716c', category: 'Structures' },
    { type: 'elevator', label: 'Elevator', icon: '🛗', width: 60, height: 60, color: '#6b7280', category: 'Structures' },
    { type: 'column', label: 'Column/Pillar', icon: '🏛️', width: 20, height: 20, color: '#a8a29e', category: 'Structures' },
  ],
  'Vehicles': [
    { type: 'car', label: 'Car', icon: '🚗', width: 100, height: 50, color: '#3b82f6', category: 'Vehicles' },
    { type: 'pickup-truck', label: 'Pickup Truck', icon: '🛻', width: 120, height: 55, color: '#78716c', category: 'Vehicles' },
    { type: 'suv', label: 'SUV', icon: '🚙', width: 110, height: 55, color: '#1e3a5f', category: 'Vehicles' },
    { type: 'van', label: 'Van', icon: '🚐', width: 120, height: 55, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'bus', label: 'Bus', icon: '🚌', width: 180, height: 55, color: '#eab308', category: 'Vehicles' },
    { type: 'semi-truck', label: 'Semi Truck', icon: '🚛', width: 200, height: 60, color: '#dc2626', category: 'Vehicles' },
    { type: 'police-car', label: 'Police Car', icon: '🚓', width: 100, height: 50, color: '#1e293b', category: 'Vehicles' },
    { type: 'ambulance', label: 'Ambulance', icon: '🚑', width: 120, height: 55, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'fire-truck', label: 'Fire Truck', icon: '🚒', width: 160, height: 55, color: '#dc2626', category: 'Vehicles' },
    { type: 'taxi', label: 'Taxi', icon: '🚕', width: 100, height: 50, color: '#eab308', category: 'Vehicles' },
    { type: 'motorcycle', label: 'Motorcycle', icon: '🏍️', width: 60, height: 30, color: '#1e293b', category: 'Vehicles' },
    { type: 'scooter', label: 'Scooter', icon: '🛵', width: 50, height: 25, color: '#6366f1', category: 'Vehicles' },
    { type: 'bicycle', label: 'Bicycle', icon: '🚲', width: 50, height: 30, color: '#059669', category: 'Vehicles' },
    { type: 'boat', label: 'Boat', icon: '🚤', width: 120, height: 50, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'atv', label: 'ATV', icon: '🏎️', width: 60, height: 40, color: '#16a34a', category: 'Vehicles' },
  ],
  'Outdoor': [
    { type: 'tree', label: 'Tree', icon: '🌳', width: 50, height: 50, color: '#16a34a', category: 'Outdoor' },
    { type: 'bush', label: 'Bush', icon: '🌿', width: 40, height: 30, color: '#22c55e', category: 'Outdoor' },
    { type: 'fence', label: 'Fence', icon: '🏗️', width: 120, height: 10, color: '#78716c', category: 'Outdoor' },
    { type: 'streetlight', label: 'Streetlight', icon: '🔦', width: 20, height: 20, color: '#facc15', category: 'Outdoor' },
    { type: 'fire-hydrant', label: 'Fire Hydrant', icon: '🧯', width: 20, height: 25, color: '#dc2626', category: 'Outdoor' },
    { type: 'dumpster', label: 'Dumpster', icon: '🗑️', width: 60, height: 40, color: '#4b5563', category: 'Outdoor' },
    { type: 'bench', label: 'Bench', icon: '🪑', width: 80, height: 25, color: '#92400e', category: 'Outdoor' },
    { type: 'sidewalk', label: 'Sidewalk', icon: '⬜', width: 120, height: 40, color: '#d1d5db', category: 'Outdoor' },
    { type: 'road', label: 'Road', icon: '🛣️', width: 150, height: 60, color: '#374151', category: 'Outdoor' },
    { type: 'mailbox', label: 'Mailbox', icon: '📮', width: 20, height: 25, color: '#2563eb', category: 'Outdoor' },
    { type: 'manhole', label: 'Manhole', icon: '⭕', width: 30, height: 30, color: '#6b7280', category: 'Outdoor' },
    { type: 'trash-can', label: 'Trash Can', icon: '🗑️', width: 25, height: 25, color: '#57534e', category: 'Outdoor' },
    { type: 'parking-spot', label: 'Parking Spot', icon: '🅿️', width: 60, height: 120, color: '#94a3b8', category: 'Outdoor' },
    { type: 'crosswalk', label: 'Crosswalk', icon: '🚶', width: 80, height: 30, color: '#f5f5f4', category: 'Outdoor' },
    { type: 'traffic-cone', label: 'Traffic Cone', icon: '🔺', width: 15, height: 15, color: '#f97316', category: 'Outdoor' },
    { type: 'barrier', label: 'Barrier', icon: '🚧', width: 80, height: 10, color: '#f59e0b', category: 'Outdoor' },
    { type: 'median', label: 'Median', icon: '➖', width: 120, height: 15, color: '#d1d5db', category: 'Outdoor' },
    { type: 'curb', label: 'Curb', icon: '▫️', width: 100, height: 8, color: '#9ca3af', category: 'Outdoor' },
  ],
  'Kitchen & Bath': [
    { type: 'stove', label: 'Stove', icon: '🍳', width: 60, height: 60, color: '#d1d5db', category: 'Kitchen & Bath' },
    { type: 'fridge', label: 'Fridge', icon: '🧊', width: 60, height: 70, color: '#e2e8f0', category: 'Kitchen & Bath' },
    { type: 'sink', label: 'Sink', icon: '🚰', width: 50, height: 40, color: '#94a3b8', category: 'Kitchen & Bath' },
    { type: 'microwave', label: 'Microwave', icon: '📦', width: 40, height: 30, color: '#475569', category: 'Kitchen & Bath' },
    { type: 'dishwasher', label: 'Dishwasher', icon: '🫧', width: 60, height: 60, color: '#cbd5e1', category: 'Kitchen & Bath' },
    { type: 'counter', label: 'Counter', icon: '▬', width: 120, height: 40, color: '#a8a29e', category: 'Kitchen & Bath' },
    { type: 'bathtub', label: 'Bathtub', icon: '🛁', width: 80, height: 50, color: '#e2e8f0', category: 'Kitchen & Bath' },
    { type: 'toilet', label: 'Toilet', icon: '🚽', width: 40, height: 50, color: '#f5f5f4', category: 'Kitchen & Bath' },
    { type: 'shower', label: 'Shower', icon: '🚿', width: 60, height: 60, color: '#bfdbfe', category: 'Kitchen & Bath' },
    { type: 'washer-dryer', label: 'Washer/Dryer', icon: '🌀', width: 60, height: 60, color: '#e2e8f0', category: 'Kitchen & Bath' },
  ],
  'Office': [
    { type: 'desk', label: 'Desk', icon: '🪵', width: 100, height: 60, color: '#92400e', category: 'Office' },
    { type: 'office-chair', label: 'Office Chair', icon: '🪑', width: 40, height: 40, color: '#1e293b', category: 'Office' },
    { type: 'computer', label: 'Computer', icon: '💻', width: 40, height: 30, color: '#334155', category: 'Office' },
    { type: 'filing-cabinet', label: 'Filing Cabinet', icon: '🗄️', width: 40, height: 50, color: '#6b7280', category: 'Office' },
    { type: 'bookshelf', label: 'Bookshelf', icon: '📚', width: 80, height: 30, color: '#78716c', category: 'Office' },
    { type: 'printer', label: 'Printer', icon: '🖨️', width: 40, height: 35, color: '#d1d5db', category: 'Office' },
    { type: 'whiteboard', label: 'Whiteboard', icon: '📋', width: 100, height: 8, color: '#f5f5f4', category: 'Office' },
    { type: 'safe', label: 'Safe', icon: '🔒', width: 40, height: 40, color: '#374151', category: 'Office' },
    { type: 'lamp', label: 'Lamp', icon: '💡', width: 20, height: 20, color: '#fbbf24', category: 'Office' },
    { type: 'tv', label: 'TV/Monitor', icon: '🖥️', width: 60, height: 40, color: '#1e293b', category: 'Office' },
  ],
  'Medical': [
    { type: 'hospital-bed', label: 'Hospital Bed', icon: '🛏️', width: 120, height: 60, color: '#e2e8f0', category: 'Medical' },
    { type: 'gurney', label: 'Gurney', icon: '🛒', width: 100, height: 40, color: '#d1d5db', category: 'Medical' },
    { type: 'iv-stand', label: 'IV Stand', icon: '💉', width: 15, height: 15, color: '#94a3b8', category: 'Medical' },
    { type: 'wheelchair', label: 'Wheelchair', icon: '♿', width: 40, height: 40, color: '#475569', category: 'Medical' },
    { type: 'med-cabinet', label: 'Med Cabinet', icon: '💊', width: 40, height: 30, color: '#f5f5f4', category: 'Medical' },
    { type: 'defibrillator', label: 'Defibrillator', icon: '⚡', width: 25, height: 25, color: '#dc2626', category: 'Medical' },
    { type: 'first-aid', label: 'First Aid Kit', icon: '🏥', width: 25, height: 20, color: '#dc2626', category: 'Medical' },
    { type: 'oxygen-tank', label: 'Oxygen Tank', icon: '🫁', width: 20, height: 30, color: '#22d3ee', category: 'Medical' },
  ],
  'Garage & Workshop': [
    { type: 'workbench', label: 'Workbench', icon: '🔨', width: 100, height: 50, color: '#78716c', category: 'Garage & Workshop' },
    { type: 'toolbox', label: 'Toolbox', icon: '🧰', width: 35, height: 25, color: '#dc2626', category: 'Garage & Workshop' },
    { type: 'shelving', label: 'Shelving', icon: '🏗️', width: 80, height: 30, color: '#6b7280', category: 'Garage & Workshop' },
    { type: 'ladder', label: 'Ladder', icon: '🪜', width: 25, height: 80, color: '#d97706', category: 'Garage & Workshop' },
    { type: 'generator', label: 'Generator', icon: '🔋', width: 50, height: 40, color: '#f59e0b', category: 'Garage & Workshop' },
    { type: 'electrical-panel', label: 'Elec. Panel', icon: '⚡', width: 30, height: 40, color: '#6b7280', category: 'Garage & Workshop' },
    { type: 'water-heater', label: 'Water Heater', icon: '🔥', width: 40, height: 40, color: '#e2e8f0', category: 'Garage & Workshop' },
    { type: 'furnace', label: 'Furnace', icon: '♨️', width: 50, height: 50, color: '#78716c', category: 'Garage & Workshop' },
  ],
  'Lighting & Safety': [
    { type: 'ceiling-light', label: 'Ceiling Light', icon: '💡', width: 20, height: 20, color: '#fbbf24', category: 'Lighting & Safety' },
    { type: 'floor-lamp', label: 'Floor Lamp', icon: '🔦', width: 15, height: 15, color: '#fbbf24', category: 'Lighting & Safety' },
    { type: 'spotlight', label: 'Spotlight', icon: '🔆', width: 15, height: 15, color: '#f59e0b', category: 'Lighting & Safety' },
    { type: 'exit-sign', label: 'Exit Sign', icon: '🚪', width: 30, height: 15, color: '#22c55e', category: 'Lighting & Safety' },
    { type: 'security-camera', label: 'Security Cam', icon: '📹', width: 15, height: 15, color: '#1e293b', category: 'Lighting & Safety' },
    { type: 'smoke-detector', label: 'Smoke Detector', icon: '🔴', width: 12, height: 12, color: '#f5f5f4', category: 'Lighting & Safety' },
    { type: 'sprinkler', label: 'Sprinkler', icon: '💧', width: 12, height: 12, color: '#3b82f6', category: 'Lighting & Safety' },
  ],
  'Scene Markers': [
    { type: 'crime-tape', label: 'Crime Tape', icon: '🟡', width: 150, height: 8, color: '#eab308', category: 'Scene Markers' },
    { type: 'cone-marker', label: 'Cone Marker', icon: '🔺', width: 20, height: 20, color: '#f97316', category: 'Scene Markers' },
    { type: 'photo-placard', label: 'Photo Placard', icon: '📸', width: 20, height: 15, color: '#f5f5f4', category: 'Scene Markers' },
    { type: 'scale-ruler', label: 'Scale Ruler', icon: '📏', width: 60, height: 8, color: '#1e293b', category: 'Scene Markers' },
    { type: 'compass-rose', label: 'Compass Rose', icon: '🧭', width: 40, height: 40, color: '#475569', category: 'Scene Markers' },
    { type: 'north-arrow', label: 'North Arrow', icon: '⬆️', width: 30, height: 40, color: '#dc2626', category: 'Scene Markers' },
  ],
};
