import { SceneObjectType } from '@/store/SceneContext';

export interface ObjectTemplate {
  type: SceneObjectType;
  label: string;
  icon: string;
  width: number;
  height: number;
  color: string;
  category: string;
}

export const objectLibrary: Record<string, ObjectTemplate[]> = {
  'Bodies': [
    { type: 'body-outline', label: 'Body Outline', icon: '🧍', width: 60, height: 120, color: '#ef4444', category: 'Bodies' },
    { type: 'body-standing', label: 'Standing', icon: '🧑', width: 40, height: 80, color: '#ef4444', category: 'Bodies' },
    { type: 'body-prone', label: 'Prone', icon: '🏊', width: 120, height: 40, color: '#ef4444', category: 'Bodies' },
    { type: 'body-seated', label: 'Seated', icon: '🧘', width: 50, height: 60, color: '#ef4444', category: 'Bodies' },
    { type: 'body-fetal', label: 'Fetal Position', icon: '🫃', width: 60, height: 50, color: '#ef4444', category: 'Bodies' },
    { type: 'body-child', label: 'Child', icon: '🧒', width: 35, height: 65, color: '#ef4444', category: 'Bodies' },
    { type: 'body-crawling', label: 'Crawling', icon: '🐛', width: 90, height: 35, color: '#ef4444', category: 'Bodies' },
    { type: 'body-kneeling', label: 'Kneeling', icon: '🧎', width: 40, height: 70, color: '#ef4444', category: 'Bodies' },
  ],
  'Weapons': [
    { type: 'knife', label: 'Knife', icon: '🔪', width: 40, height: 15, color: '#94a3b8', category: 'Weapons' },
    { type: 'gun', label: 'Handgun', icon: '🔫', width: 50, height: 30, color: '#475569', category: 'Weapons' },
    { type: 'rifle', label: 'Rifle', icon: '🎯', width: 100, height: 20, color: '#374151', category: 'Weapons' },
    { type: 'shotgun', label: 'Shotgun', icon: '💥', width: 90, height: 18, color: '#44403c', category: 'Weapons' },
    { type: 'bat', label: 'Bat/Club', icon: '🏏', width: 60, height: 12, color: '#78716c', category: 'Weapons' },
    { type: 'crowbar', label: 'Crowbar', icon: '🪝', width: 50, height: 10, color: '#475569', category: 'Weapons' },
    { type: 'rope', label: 'Rope/Cord', icon: '🪢', width: 80, height: 8, color: '#a8a29e', category: 'Weapons' },
    { type: 'axe', label: 'Axe', icon: '🪓', width: 45, height: 20, color: '#6b7280', category: 'Weapons' },
    { type: 'hammer', label: 'Hammer', icon: '🔨', width: 35, height: 15, color: '#78716c', category: 'Weapons' },
    { type: 'taser', label: 'Taser', icon: '⚡', width: 30, height: 18, color: '#eab308', category: 'Weapons' },
    { type: 'pepper-spray', label: 'Pepper Spray', icon: '🌶️', width: 15, height: 20, color: '#dc2626', category: 'Weapons' },
    { type: 'brass-knuckles', label: 'Brass Knuckles', icon: '✊', width: 25, height: 15, color: '#d4a017', category: 'Weapons' },
    { type: 'bullet-casing', label: 'Casing', icon: '⊙', width: 10, height: 10, color: '#d97706', category: 'Weapons' },
    { type: 'bullet-hole', label: 'Bullet Hole', icon: '⊗', width: 12, height: 12, color: '#1e293b', category: 'Weapons' },
  ],
  'Evidence': [
    { type: 'evidence-marker', label: 'Marker', icon: '🔶', width: 30, height: 30, color: '#eab308', category: 'Evidence' },
    { type: 'blood-stain', label: 'Blood Stain', icon: '🩸', width: 40, height: 30, color: '#dc2626', category: 'Evidence' },
    { type: 'footprint', label: 'Footprint', icon: '👣', width: 25, height: 50, color: '#78716c', category: 'Evidence' },
    { type: 'tire-mark', label: 'Tire Mark', icon: '〰️', width: 120, height: 20, color: '#1c1917', category: 'Evidence' },
    { type: 'fingerprint', label: 'Fingerprint', icon: '🖐️', width: 20, height: 25, color: '#a3a3a3', category: 'Evidence' },
    { type: 'hair-fiber', label: 'Hair/Fiber', icon: '🧬', width: 15, height: 15, color: '#92400e', category: 'Evidence' },
    { type: 'clothing', label: 'Clothing', icon: '👕', width: 40, height: 40, color: '#6366f1', category: 'Evidence' },
    { type: 'document-evidence', label: 'Document', icon: '📄', width: 30, height: 40, color: '#f5f5f4', category: 'Evidence' },
    { type: 'drug-paraphernalia', label: 'Drugs/Para.', icon: '💊', width: 20, height: 20, color: '#f97316', category: 'Evidence' },
    { type: 'glass-fragment', label: 'Glass', icon: '💎', width: 25, height: 20, color: '#67e8f9', category: 'Evidence' },
    { type: 'shell-casing', label: 'Shell Casing', icon: '🔩', width: 12, height: 12, color: '#ca8a04', category: 'Evidence' },
    { type: 'dna-sample', label: 'DNA Sample', icon: '🧪', width: 15, height: 15, color: '#22c55e', category: 'Evidence' },
    { type: 'phone', label: 'Phone', icon: '📱', width: 20, height: 35, color: '#1e293b', category: 'Evidence' },
    { type: 'camera', label: 'Camera', icon: '📷', width: 30, height: 25, color: '#334155', category: 'Evidence' },
    { type: 'id-card', label: 'ID Card', icon: '🪪', width: 35, height: 22, color: '#e2e8f0', category: 'Evidence' },
    { type: 'bag', label: 'Bag', icon: '👜', width: 35, height: 30, color: '#78716c', category: 'Evidence' },
    { type: 'wallet', label: 'Wallet', icon: '👛', width: 20, height: 15, color: '#78716c', category: 'Evidence' },
    { type: 'keys', label: 'Keys', icon: '🔑', width: 15, height: 15, color: '#d4d4d8', category: 'Evidence' },
    { type: 'cigarette-butt', label: 'Cigarette Butt', icon: '🚬', width: 10, height: 10, color: '#a8a29e', category: 'Evidence' },
    { type: 'weapon-sheath', label: 'Sheath/Holster', icon: '🔰', width: 25, height: 15, color: '#57534e', category: 'Evidence' },
    { type: 'shoe', label: 'Shoe', icon: '👟', width: 25, height: 15, color: '#57534e', category: 'Evidence' },
    { type: 'glasses', label: 'Glasses', icon: '👓', width: 20, height: 10, color: '#1e293b', category: 'Evidence' },
    { type: 'jewelry', label: 'Jewelry', icon: '💍', width: 12, height: 12, color: '#d4a017', category: 'Evidence' },
    { type: 'bottle', label: 'Bottle', icon: '🍾', width: 15, height: 25, color: '#22c55e', category: 'Evidence' },
    { type: 'can', label: 'Can', icon: '🥫', width: 12, height: 15, color: '#dc2626', category: 'Evidence' },
    { type: 'syringe', label: 'Syringe', icon: '💉', width: 20, height: 8, color: '#94a3b8', category: 'Evidence' },
    { type: 'tape-roll', label: 'Tape Roll', icon: '🎞️', width: 15, height: 15, color: '#6b7280', category: 'Evidence' },
    { type: 'flashlight-ev', label: 'Flashlight', icon: '🔦', width: 20, height: 10, color: '#1e293b', category: 'Evidence' },
  ],
  'Furniture': [
    { type: 'bed', label: 'Bed', icon: '🛏️', width: 120, height: 80, color: '#7c3aed', category: 'Furniture' },
    { type: 'table', label: 'Table', icon: '🪑', width: 80, height: 60, color: '#92400e', category: 'Furniture' },
    { type: 'chair', label: 'Chair', icon: '💺', width: 40, height: 40, color: '#92400e', category: 'Furniture' },
    { type: 'sofa', label: 'Sofa', icon: '🛋️', width: 120, height: 50, color: '#6d28d9', category: 'Furniture' },
    { type: 'cabinet', label: 'Cabinet', icon: '🗄️', width: 60, height: 30, color: '#78716c', category: 'Furniture' },
    { type: 'nightstand', label: 'Nightstand', icon: '🗃️', width: 35, height: 35, color: '#78716c', category: 'Furniture' },
    { type: 'dresser', label: 'Dresser', icon: '🪟', width: 80, height: 40, color: '#92400e', category: 'Furniture' },
    { type: 'bookcase', label: 'Bookcase', icon: '📚', width: 80, height: 30, color: '#78716c', category: 'Furniture' },
    { type: 'rug', label: 'Rug/Carpet', icon: '🟫', width: 100, height: 70, color: '#a16207', category: 'Furniture' },
    { type: 'mirror', label: 'Mirror', icon: '🪞', width: 40, height: 8, color: '#bfdbfe', category: 'Furniture' },
    { type: 'tv-stand', label: 'TV Stand', icon: '📺', width: 100, height: 30, color: '#1e293b', category: 'Furniture' },
    { type: 'coffee-table', label: 'Coffee Table', icon: '☕', width: 70, height: 45, color: '#92400e', category: 'Furniture' },
    { type: 'dining-table', label: 'Dining Table', icon: '🍽️', width: 120, height: 80, color: '#78350f', category: 'Furniture' },
    { type: 'recliner', label: 'Recliner', icon: '🪑', width: 50, height: 55, color: '#6d28d9', category: 'Furniture' },
    { type: 'ottoman', label: 'Ottoman', icon: '🟤', width: 35, height: 35, color: '#a16207', category: 'Furniture' },
    { type: 'wardrobe', label: 'Wardrobe', icon: '🚪', width: 90, height: 40, color: '#78716c', category: 'Furniture' },
    { type: 'crib', label: 'Crib', icon: '👶', width: 70, height: 45, color: '#f5f5f4', category: 'Furniture' },
    { type: 'bunk-bed', label: 'Bunk Bed', icon: '🛏️', width: 80, height: 60, color: '#92400e', category: 'Furniture' },
    { type: 'futon', label: 'Futon', icon: '🛋️', width: 100, height: 55, color: '#475569', category: 'Furniture' },
  ],
  'Structures': [
    { type: 'door', label: 'Door', icon: '🚪', width: 60, height: 10, color: '#92400e', category: 'Structures' },
    { type: 'sliding-door', label: 'Sliding Door', icon: '↔️', width: 80, height: 10, color: '#94a3b8', category: 'Structures' },
    { type: 'garage-door', label: 'Garage Door', icon: '🏠', width: 120, height: 12, color: '#d1d5db', category: 'Structures' },
    { type: 'archway', label: 'Archway', icon: '🌉', width: 60, height: 10, color: '#a8a29e', category: 'Structures' },
    { type: 'french-door', label: 'French Door', icon: '🏠', width: 70, height: 10, color: '#f5f5f4', category: 'Structures' },
    { type: 'revolving-door', label: 'Revolving Door', icon: '🔄', width: 50, height: 50, color: '#94a3b8', category: 'Structures' },
    { type: 'window', label: 'Window', icon: '🪟', width: 60, height: 8, color: '#38bdf8', category: 'Structures' },
    { type: 'skylight', label: 'Skylight', icon: '☀️', width: 50, height: 50, color: '#7dd3fc', category: 'Structures' },
    { type: 'wall', label: 'Wall', icon: '▬', width: 120, height: 10, color: '#334155', category: 'Structures' },
    { type: 'partition-wall', label: 'Partition Wall', icon: '┃', width: 80, height: 8, color: '#94a3b8', category: 'Structures' },
    { type: 'half-wall', label: 'Half Wall', icon: '▭', width: 80, height: 6, color: '#a8a29e', category: 'Structures' },
    { type: 'stairs', label: 'Stairs', icon: '🪜', width: 60, height: 80, color: '#78716c', category: 'Structures' },
    { type: 'fire-escape', label: 'Fire Escape', icon: '🔥', width: 50, height: 70, color: '#6b7280', category: 'Structures' },
    { type: 'elevator', label: 'Elevator', icon: '🛗', width: 60, height: 60, color: '#6b7280', category: 'Structures' },
    { type: 'column', label: 'Column/Pillar', icon: '🏛️', width: 20, height: 20, color: '#a8a29e', category: 'Structures' },
    { type: 'balcony', label: 'Balcony', icon: '🏗️', width: 80, height: 30, color: '#a8a29e', category: 'Structures' },
  ],
  'Vehicles': [
    { type: 'car', label: 'Car', icon: '🚗', width: 100, height: 50, color: '#3b82f6', category: 'Vehicles' },
    { type: 'pickup-truck', label: 'Pickup Truck', icon: '🛻', width: 120, height: 55, color: '#78716c', category: 'Vehicles' },
    { type: 'suv', label: 'SUV', icon: '🚙', width: 110, height: 55, color: '#1e3a5f', category: 'Vehicles' },
    { type: 'van', label: 'Van', icon: '🚐', width: 120, height: 55, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'bus', label: 'Bus', icon: '🚌', width: 180, height: 55, color: '#eab308', category: 'Vehicles' },
    { type: 'semi-truck', label: 'Semi Truck', icon: '🚛', width: 200, height: 60, color: '#dc2626', category: 'Vehicles' },
    { type: 'police-car', label: 'Police Car', icon: '🚓', width: 100, height: 50, color: '#1e293b', category: 'Vehicles' },
    { type: 'ambulance', label: 'Ambulance', icon: '🚑', width: 120, height: 55, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'fire-truck', label: 'Fire Truck', icon: '🚒', width: 160, height: 55, color: '#dc2626', category: 'Vehicles' },
    { type: 'taxi', label: 'Taxi', icon: '🚕', width: 100, height: 50, color: '#eab308', category: 'Vehicles' },
    { type: 'motorcycle', label: 'Motorcycle', icon: '🏍️', width: 60, height: 30, color: '#1e293b', category: 'Vehicles' },
    { type: 'scooter', label: 'Scooter', icon: '🛵', width: 50, height: 25, color: '#6366f1', category: 'Vehicles' },
    { type: 'bicycle', label: 'Bicycle', icon: '🚲', width: 50, height: 30, color: '#059669', category: 'Vehicles' },
    { type: 'boat', label: 'Boat', icon: '🚤', width: 120, height: 50, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'atv', label: 'ATV', icon: '🏎️', width: 60, height: 40, color: '#16a34a', category: 'Vehicles' },
    { type: 'golf-cart', label: 'Golf Cart', icon: '🏌️', width: 70, height: 40, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'forklift', label: 'Forklift', icon: '🏗️', width: 60, height: 40, color: '#eab308', category: 'Vehicles' },
    { type: 'tractor', label: 'Tractor', icon: '🚜', width: 80, height: 50, color: '#16a34a', category: 'Vehicles' },
    { type: 'rv', label: 'RV', icon: '🚐', width: 160, height: 60, color: '#f5f5f4', category: 'Vehicles' },
    { type: 'limo', label: 'Limousine', icon: '🚙', width: 160, height: 50, color: '#1e293b', category: 'Vehicles' },
    { type: 'helicopter', label: 'Helicopter', icon: '🚁', width: 80, height: 80, color: '#475569', category: 'Vehicles' },
    { type: 'jet-ski', label: 'Jet Ski', icon: '🚤', width: 50, height: 25, color: '#3b82f6', category: 'Vehicles' },
  ],
  'Outdoor': [
    { type: 'tree', label: 'Tree', icon: '🌳', width: 50, height: 50, color: '#16a34a', category: 'Outdoor' },
    { type: 'bush', label: 'Bush', icon: '🌿', width: 40, height: 30, color: '#22c55e', category: 'Outdoor' },
    { type: 'fence', label: 'Fence', icon: '🏗️', width: 120, height: 10, color: '#78716c', category: 'Outdoor' },
    { type: 'streetlight', label: 'Streetlight', icon: '🔦', width: 20, height: 20, color: '#facc15', category: 'Outdoor' },
    { type: 'fire-hydrant', label: 'Fire Hydrant', icon: '🧯', width: 20, height: 25, color: '#dc2626', category: 'Outdoor' },
    { type: 'dumpster', label: 'Dumpster', icon: '🗑️', width: 60, height: 40, color: '#4b5563', category: 'Outdoor' },
    { type: 'bench', label: 'Bench', icon: '🪑', width: 80, height: 25, color: '#92400e', category: 'Outdoor' },
    { type: 'sidewalk', label: 'Sidewalk', icon: '⬜', width: 120, height: 40, color: '#d1d5db', category: 'Outdoor' },
    { type: 'road', label: 'Road', icon: '🛣️', width: 150, height: 60, color: '#374151', category: 'Outdoor' },
    { type: 'mailbox', label: 'Mailbox', icon: '📮', width: 20, height: 25, color: '#2563eb', category: 'Outdoor' },
    { type: 'manhole', label: 'Manhole', icon: '⭕', width: 30, height: 30, color: '#6b7280', category: 'Outdoor' },
    { type: 'trash-can', label: 'Trash Can', icon: '🗑️', width: 25, height: 25, color: '#57534e', category: 'Outdoor' },
    { type: 'parking-spot', label: 'Parking Spot', icon: '🅿️', width: 60, height: 120, color: '#94a3b8', category: 'Outdoor' },
    { type: 'crosswalk', label: 'Crosswalk', icon: '🚶', width: 80, height: 30, color: '#f5f5f4', category: 'Outdoor' },
    { type: 'traffic-cone', label: 'Traffic Cone', icon: '🔺', width: 15, height: 15, color: '#f97316', category: 'Outdoor' },
    { type: 'barrier', label: 'Barrier', icon: '🚧', width: 80, height: 10, color: '#f59e0b', category: 'Outdoor' },
    { type: 'median', label: 'Median', icon: '➖', width: 120, height: 15, color: '#d1d5db', category: 'Outdoor' },
    { type: 'curb', label: 'Curb', icon: '▫️', width: 100, height: 8, color: '#9ca3af', category: 'Outdoor' },
    { type: 'gazebo', label: 'Gazebo', icon: '⛺', width: 80, height: 80, color: '#92400e', category: 'Outdoor' },
    { type: 'flagpole', label: 'Flagpole', icon: '🚩', width: 10, height: 10, color: '#6b7280', category: 'Outdoor' },
    { type: 'utility-pole', label: 'Utility Pole', icon: '🔌', width: 15, height: 15, color: '#78716c', category: 'Outdoor' },
    { type: 'storm-drain', label: 'Storm Drain', icon: '🕳️', width: 25, height: 12, color: '#374151', category: 'Outdoor' },
    { type: 'speed-bump', label: 'Speed Bump', icon: '⏫', width: 80, height: 10, color: '#eab308', category: 'Outdoor' },
    { type: 'guard-rail', label: 'Guard Rail', icon: '🛡️', width: 100, height: 8, color: '#94a3b8', category: 'Outdoor' },
  ],
  'Kitchen & Bath': [
    { type: 'stove', label: 'Stove', icon: '🍳', width: 60, height: 60, color: '#d1d5db', category: 'Kitchen & Bath' },
    { type: 'fridge', label: 'Fridge', icon: '🧊', width: 60, height: 70, color: '#e2e8f0', category: 'Kitchen & Bath' },
    { type: 'sink', label: 'Sink', icon: '🚰', width: 50, height: 40, color: '#94a3b8', category: 'Kitchen & Bath' },
    { type: 'microwave', label: 'Microwave', icon: '📦', width: 40, height: 30, color: '#475569', category: 'Kitchen & Bath' },
    { type: 'dishwasher', label: 'Dishwasher', icon: '🫧', width: 60, height: 60, color: '#cbd5e1', category: 'Kitchen & Bath' },
    { type: 'counter', label: 'Counter', icon: '▬', width: 120, height: 40, color: '#a8a29e', category: 'Kitchen & Bath' },
    { type: 'kitchen-island', label: 'Kitchen Island', icon: '🏝️', width: 100, height: 60, color: '#92400e', category: 'Kitchen & Bath' },
    { type: 'pantry', label: 'Pantry', icon: '🗄️', width: 60, height: 40, color: '#78716c', category: 'Kitchen & Bath' },
    { type: 'wine-rack', label: 'Wine Rack', icon: '🍷', width: 40, height: 30, color: '#92400e', category: 'Kitchen & Bath' },
    { type: 'garbage-disposal', label: 'Garbage Disp.', icon: '♻️', width: 20, height: 20, color: '#6b7280', category: 'Kitchen & Bath' },
    { type: 'bathtub', label: 'Bathtub', icon: '🛁', width: 80, height: 50, color: '#e2e8f0', category: 'Kitchen & Bath' },
    { type: 'toilet', label: 'Toilet', icon: '🚽', width: 40, height: 50, color: '#f5f5f4', category: 'Kitchen & Bath' },
    { type: 'shower', label: 'Shower', icon: '🚿', width: 60, height: 60, color: '#bfdbfe', category: 'Kitchen & Bath' },
    { type: 'bidet', label: 'Bidet', icon: '🚰', width: 35, height: 40, color: '#f5f5f4', category: 'Kitchen & Bath' },
    { type: 'jacuzzi', label: 'Jacuzzi', icon: '♨️', width: 80, height: 80, color: '#7dd3fc', category: 'Kitchen & Bath' },
    { type: 'washer-dryer', label: 'Washer/Dryer', icon: '🌀', width: 60, height: 60, color: '#e2e8f0', category: 'Kitchen & Bath' },
    { type: 'medicine-cabinet', label: 'Med Cabinet', icon: '💊', width: 40, height: 8, color: '#f5f5f4', category: 'Kitchen & Bath' },
    { type: 'towel-rack', label: 'Towel Rack', icon: '🧴', width: 30, height: 6, color: '#94a3b8', category: 'Kitchen & Bath' },
  ],
  'Office': [
    { type: 'desk', label: 'Desk', icon: '🪵', width: 100, height: 60, color: '#92400e', category: 'Office' },
    { type: 'office-chair', label: 'Office Chair', icon: '🪑', width: 40, height: 40, color: '#1e293b', category: 'Office' },
    { type: 'computer', label: 'Computer', icon: '💻', width: 40, height: 30, color: '#334155', category: 'Office' },
    { type: 'filing-cabinet', label: 'Filing Cabinet', icon: '🗄️', width: 40, height: 50, color: '#6b7280', category: 'Office' },
    { type: 'bookshelf', label: 'Bookshelf', icon: '📚', width: 80, height: 30, color: '#78716c', category: 'Office' },
    { type: 'printer', label: 'Printer', icon: '🖨️', width: 40, height: 35, color: '#d1d5db', category: 'Office' },
    { type: 'whiteboard', label: 'Whiteboard', icon: '📋', width: 100, height: 8, color: '#f5f5f4', category: 'Office' },
    { type: 'safe', label: 'Safe', icon: '🔒', width: 40, height: 40, color: '#374151', category: 'Office' },
    { type: 'lamp', label: 'Lamp', icon: '💡', width: 20, height: 20, color: '#fbbf24', category: 'Office' },
    { type: 'tv', label: 'TV/Monitor', icon: '🖥️', width: 60, height: 40, color: '#1e293b', category: 'Office' },
    { type: 'conference-table', label: 'Conference Table', icon: '🪵', width: 160, height: 80, color: '#78350f', category: 'Office' },
    { type: 'cubicle', label: 'Cubicle', icon: '🏢', width: 80, height: 80, color: '#94a3b8', category: 'Office' },
    { type: 'water-cooler', label: 'Water Cooler', icon: '💧', width: 20, height: 20, color: '#3b82f6', category: 'Office' },
    { type: 'shredder', label: 'Shredder', icon: '📃', width: 25, height: 30, color: '#6b7280', category: 'Office' },
    { type: 'projector', label: 'Projector', icon: '📽️', width: 30, height: 25, color: '#1e293b', category: 'Office' },
    { type: 'server-rack', label: 'Server Rack', icon: '🖥️', width: 40, height: 60, color: '#1e293b', category: 'Office' },
    { type: 'reception-desk', label: 'Reception Desk', icon: '🏨', width: 120, height: 50, color: '#92400e', category: 'Office' },
    { type: 'copier', label: 'Copier', icon: '🖨️', width: 50, height: 45, color: '#d1d5db', category: 'Office' },
  ],
  'Medical': [
    { type: 'hospital-bed', label: 'Hospital Bed', icon: '🛏️', width: 120, height: 60, color: '#e2e8f0', category: 'Medical' },
    { type: 'gurney', label: 'Gurney', icon: '🛒', width: 100, height: 40, color: '#d1d5db', category: 'Medical' },
    { type: 'iv-stand', label: 'IV Stand', icon: '💉', width: 15, height: 15, color: '#94a3b8', category: 'Medical' },
    { type: 'wheelchair', label: 'Wheelchair', icon: '♿', width: 40, height: 40, color: '#475569', category: 'Medical' },
    { type: 'med-cabinet', label: 'Med Cabinet', icon: '💊', width: 40, height: 30, color: '#f5f5f4', category: 'Medical' },
    { type: 'defibrillator', label: 'Defibrillator', icon: '⚡', width: 25, height: 25, color: '#dc2626', category: 'Medical' },
    { type: 'first-aid', label: 'First Aid Kit', icon: '🏥', width: 25, height: 20, color: '#dc2626', category: 'Medical' },
    { type: 'oxygen-tank', label: 'Oxygen Tank', icon: '🫁', width: 20, height: 30, color: '#22d3ee', category: 'Medical' },
    { type: 'exam-table', label: 'Exam Table', icon: '🛏️', width: 80, height: 50, color: '#e2e8f0', category: 'Medical' },
    { type: 'x-ray-machine', label: 'X-Ray Machine', icon: '📡', width: 60, height: 60, color: '#475569', category: 'Medical' },
    { type: 'crash-cart', label: 'Crash Cart', icon: '🚨', width: 40, height: 30, color: '#dc2626', category: 'Medical' },
    { type: 'body-bag', label: 'Body Bag', icon: '⚰️', width: 80, height: 35, color: '#1e293b', category: 'Medical' },
    { type: 'stretcher', label: 'Stretcher', icon: '🛏️', width: 90, height: 35, color: '#475569', category: 'Medical' },
    { type: 'medical-waste', label: 'Medical Waste', icon: '☣️', width: 25, height: 30, color: '#dc2626', category: 'Medical' },
    { type: 'sharps-container', label: 'Sharps Container', icon: '🔴', width: 15, height: 20, color: '#dc2626', category: 'Medical' },
  ],
  'Garage & Workshop': [
    { type: 'workbench', label: 'Workbench', icon: '🔨', width: 100, height: 50, color: '#78716c', category: 'Garage & Workshop' },
    { type: 'toolbox', label: 'Toolbox', icon: '🧰', width: 35, height: 25, color: '#dc2626', category: 'Garage & Workshop' },
    { type: 'shelving', label: 'Shelving', icon: '🏗️', width: 80, height: 30, color: '#6b7280', category: 'Garage & Workshop' },
    { type: 'ladder', label: 'Ladder', icon: '🪜', width: 25, height: 80, color: '#d97706', category: 'Garage & Workshop' },
    { type: 'generator', label: 'Generator', icon: '🔋', width: 50, height: 40, color: '#f59e0b', category: 'Garage & Workshop' },
    { type: 'electrical-panel', label: 'Elec. Panel', icon: '⚡', width: 30, height: 40, color: '#6b7280', category: 'Garage & Workshop' },
    { type: 'water-heater', label: 'Water Heater', icon: '🔥', width: 40, height: 40, color: '#e2e8f0', category: 'Garage & Workshop' },
    { type: 'furnace', label: 'Furnace', icon: '♨️', width: 50, height: 50, color: '#78716c', category: 'Garage & Workshop' },
    { type: 'air-compressor', label: 'Air Compressor', icon: '💨', width: 40, height: 35, color: '#dc2626', category: 'Garage & Workshop' },
    { type: 'drill-press', label: 'Drill Press', icon: '🔩', width: 30, height: 30, color: '#6b7280', category: 'Garage & Workshop' },
    { type: 'circular-saw', label: 'Circular Saw', icon: '🪚', width: 35, height: 30, color: '#f59e0b', category: 'Garage & Workshop' },
    { type: 'welding-station', label: 'Welding Station', icon: '🔥', width: 50, height: 40, color: '#475569', category: 'Garage & Workshop' },
    { type: 'vise', label: 'Vise', icon: '🗜️', width: 20, height: 20, color: '#6b7280', category: 'Garage & Workshop' },
    { type: 'jack-stand', label: 'Jack Stand', icon: '🔺', width: 15, height: 20, color: '#f97316', category: 'Garage & Workshop' },
    { type: 'oil-drum', label: 'Oil Drum', icon: '🛢️', width: 30, height: 30, color: '#1e293b', category: 'Garage & Workshop' },
  ],
  'Lighting & Safety': [
    { type: 'ceiling-light', label: 'Ceiling Light', icon: '💡', width: 20, height: 20, color: '#fbbf24', category: 'Lighting & Safety' },
    { type: 'floor-lamp', label: 'Floor Lamp', icon: '🔦', width: 15, height: 15, color: '#fbbf24', category: 'Lighting & Safety' },
    { type: 'spotlight', label: 'Spotlight', icon: '🔆', width: 15, height: 15, color: '#f59e0b', category: 'Lighting & Safety' },
    { type: 'flood-light', label: 'Flood Light', icon: '☀️', width: 20, height: 15, color: '#fbbf24', category: 'Lighting & Safety' },
    { type: 'exit-sign', label: 'Exit Sign', icon: '🚪', width: 30, height: 15, color: '#22c55e', category: 'Lighting & Safety' },
    { type: 'emergency-light', label: 'Emergency Light', icon: '🚨', width: 20, height: 12, color: '#dc2626', category: 'Lighting & Safety' },
    { type: 'strobe-light', label: 'Strobe Light', icon: '💫', width: 15, height: 15, color: '#f59e0b', category: 'Lighting & Safety' },
    { type: 'security-camera', label: 'Security Cam', icon: '📹', width: 15, height: 15, color: '#1e293b', category: 'Lighting & Safety' },
    { type: 'motion-sensor', label: 'Motion Sensor', icon: '📡', width: 12, height: 12, color: '#475569', category: 'Lighting & Safety' },
    { type: 'smoke-detector', label: 'Smoke Detector', icon: '🔴', width: 12, height: 12, color: '#f5f5f4', category: 'Lighting & Safety' },
    { type: 'sprinkler', label: 'Sprinkler', icon: '💧', width: 12, height: 12, color: '#3b82f6', category: 'Lighting & Safety' },
    { type: 'fire-extinguisher', label: 'Fire Extinguisher', icon: '🧯', width: 15, height: 25, color: '#dc2626', category: 'Lighting & Safety' },
    { type: 'alarm-panel', label: 'Alarm Panel', icon: '🔔', width: 25, height: 20, color: '#6b7280', category: 'Lighting & Safety' },
  ],
  'Scene Markers': [
    { type: 'crime-tape', label: 'Crime Tape', icon: '🟡', width: 150, height: 8, color: '#eab308', category: 'Scene Markers' },
    { type: 'cone-marker', label: 'Cone Marker', icon: '🔺', width: 20, height: 20, color: '#f97316', category: 'Scene Markers' },
    { type: 'photo-placard', label: 'Photo Placard', icon: '📸', width: 20, height: 15, color: '#f5f5f4', category: 'Scene Markers' },
    { type: 'scale-ruler', label: 'Scale Ruler', icon: '📏', width: 60, height: 8, color: '#1e293b', category: 'Scene Markers' },
    { type: 'compass-rose', label: 'Compass Rose', icon: '🧭', width: 40, height: 40, color: '#475569', category: 'Scene Markers' },
    { type: 'north-arrow', label: 'North Arrow', icon: '⬆️', width: 30, height: 40, color: '#dc2626', category: 'Scene Markers' },
    { type: 'measurement-marker', label: 'Measurement', icon: '📐', width: 25, height: 25, color: '#eab308', category: 'Scene Markers' },
    { type: 'blood-spatter-card', label: 'Spatter Card', icon: '🃏', width: 20, height: 15, color: '#dc2626', category: 'Scene Markers' },
    { type: 'trajectory-rod', label: 'Trajectory Rod', icon: '🪡', width: 60, height: 5, color: '#f97316', category: 'Scene Markers' },
    { type: 'grid-marker', label: 'Grid Marker', icon: '🔲', width: 30, height: 30, color: '#475569', category: 'Scene Markers' },
    { type: 'entry-point', label: 'Entry Point', icon: '🟢', width: 20, height: 20, color: '#22c55e', category: 'Scene Markers' },
    { type: 'exit-point', label: 'Exit Point', icon: '🔴', width: 20, height: 20, color: '#dc2626', category: 'Scene Markers' },
  ],
  'Hazmat & Industrial': [
    { type: 'hazmat-barrel', label: 'Hazmat Barrel', icon: '🛢️', width: 30, height: 30, color: '#eab308', category: 'Hazmat & Industrial' },
    { type: 'chemical-spill', label: 'Chemical Spill', icon: '🧪', width: 60, height: 40, color: '#22c55e', category: 'Hazmat & Industrial' },
    { type: 'gas-leak', label: 'Gas Leak', icon: '💨', width: 40, height: 40, color: '#94a3b8', category: 'Hazmat & Industrial' },
    { type: 'biohazard-zone', label: 'Biohazard Zone', icon: '☣️', width: 50, height: 50, color: '#f97316', category: 'Hazmat & Industrial' },
    { type: 'radiation-sign', label: 'Radiation Sign', icon: '☢️', width: 30, height: 30, color: '#eab308', category: 'Hazmat & Industrial' },
    { type: 'caution-sign', label: 'Caution Sign', icon: '⚠️', width: 25, height: 30, color: '#eab308', category: 'Hazmat & Industrial' },
  ],
  'Recreation': [
    { type: 'playground-swing', label: 'Swing Set', icon: '🎠', width: 60, height: 40, color: '#dc2626', category: 'Recreation' },
    { type: 'slide', label: 'Slide', icon: '🛝', width: 40, height: 60, color: '#3b82f6', category: 'Recreation' },
    { type: 'picnic-table', label: 'Picnic Table', icon: '🪵', width: 80, height: 50, color: '#92400e', category: 'Recreation' },
    { type: 'pool', label: 'Pool', icon: '🏊', width: 120, height: 60, color: '#38bdf8', category: 'Recreation' },
    { type: 'hot-tub', label: 'Hot Tub', icon: '♨️', width: 60, height: 60, color: '#7dd3fc', category: 'Recreation' },
    { type: 'trampoline', label: 'Trampoline', icon: '⭕', width: 60, height: 60, color: '#1e293b', category: 'Recreation' },
    { type: 'basketball-hoop', label: 'Basketball Hoop', icon: '🏀', width: 25, height: 25, color: '#f97316', category: 'Recreation' },
    { type: 'grill', label: 'Grill/BBQ', icon: '🍖', width: 40, height: 35, color: '#1e293b', category: 'Recreation' },
    { type: 'sandbox', label: 'Sandbox', icon: '🏖️', width: 60, height: 60, color: '#fde68a', category: 'Recreation' },
    { type: 'seesaw', label: 'Seesaw', icon: '⚖️', width: 80, height: 20, color: '#dc2626', category: 'Recreation' },
    { type: 'soccer-goal', label: 'Soccer Goal', icon: '🥅', width: 80, height: 25, color: '#f5f5f4', category: 'Recreation' },
    { type: 'tennis-net', label: 'Tennis Net', icon: '🎾', width: 100, height: 8, color: '#22c55e', category: 'Recreation' },
    { type: 'volleyball-net', label: 'Volleyball Net', icon: '🏐', width: 100, height: 8, color: '#f5f5f4', category: 'Recreation' },
    { type: 'skate-ramp', label: 'Skate Ramp', icon: '🛹', width: 80, height: 40, color: '#78716c', category: 'Recreation' },
    { type: 'monkey-bars', label: 'Monkey Bars', icon: '🐒', width: 80, height: 30, color: '#dc2626', category: 'Recreation' },
    { type: 'firepit', label: 'Fire Pit', icon: '🔥', width: 40, height: 40, color: '#ea580c', category: 'Recreation' },
  ],
  'Animals': [
    { type: 'dog', label: 'Dog', icon: '🐕', width: 35, height: 25, color: '#92400e', category: 'Animals' },
    { type: 'cat', label: 'Cat', icon: '🐈', width: 25, height: 18, color: '#78716c', category: 'Animals' },
    { type: 'horse', label: 'Horse', icon: '🐎', width: 80, height: 40, color: '#78350f', category: 'Animals' },
    { type: 'cow', label: 'Cow', icon: '🐄', width: 80, height: 45, color: '#1e293b', category: 'Animals' },
    { type: 'pig', label: 'Pig', icon: '🐖', width: 50, height: 30, color: '#fda4af', category: 'Animals' },
    { type: 'chicken', label: 'Chicken', icon: '🐓', width: 20, height: 22, color: '#f5f5f4', category: 'Animals' },
    { type: 'bird', label: 'Bird', icon: '🐦', width: 15, height: 12, color: '#3b82f6', category: 'Animals' },
    { type: 'snake', label: 'Snake', icon: '🐍', width: 60, height: 12, color: '#16a34a', category: 'Animals' },
    { type: 'rodent', label: 'Rodent', icon: '🐀', width: 18, height: 12, color: '#57534e', category: 'Animals' },
    { type: 'fish-tank', label: 'Fish Tank', icon: '🐠', width: 50, height: 30, color: '#38bdf8', category: 'Animals' },
    { type: 'pet-bed', label: 'Pet Bed', icon: '🛏️', width: 40, height: 30, color: '#a16207', category: 'Animals' },
    { type: 'pet-crate', label: 'Pet Crate', icon: '🪺', width: 45, height: 35, color: '#475569', category: 'Animals' },
  ],
  'Tactical & Police': [
    { type: 'k9-unit', label: 'K-9 Unit', icon: '🐕‍🦺', width: 35, height: 25, color: '#1e293b', category: 'Tactical & Police' },
    { type: 'police-shield', label: 'Riot Shield', icon: '🛡️', width: 25, height: 40, color: '#1e293b', category: 'Tactical & Police' },
    { type: 'police-barricade', label: 'Barricade', icon: '🚧', width: 80, height: 12, color: '#1e40af', category: 'Tactical & Police' },
    { type: 'evidence-tent', label: 'Evidence Tent', icon: '⛺', width: 30, height: 30, color: '#eab308', category: 'Tactical & Police' },
    { type: 'cordon-post', label: 'Cordon Post', icon: '📍', width: 12, height: 12, color: '#eab308', category: 'Tactical & Police' },
    { type: 'spike-strip', label: 'Spike Strip', icon: '〰️', width: 100, height: 10, color: '#1e293b', category: 'Tactical & Police' },
    { type: 'breaching-ram', label: 'Breaching Ram', icon: '🔨', width: 50, height: 15, color: '#dc2626', category: 'Tactical & Police' },
    { type: 'body-armor', label: 'Body Armor', icon: '🦺', width: 30, height: 35, color: '#1e293b', category: 'Tactical & Police' },
    { type: 'k9-leash', label: 'K-9 Leash', icon: '🪢', width: 40, height: 6, color: '#92400e', category: 'Tactical & Police' },
    { type: 'handcuffs', label: 'Handcuffs', icon: '⛓️', width: 25, height: 12, color: '#94a3b8', category: 'Tactical & Police' },
    { type: 'baton', label: 'Baton', icon: '🥢', width: 40, height: 6, color: '#1e293b', category: 'Tactical & Police' },
    { type: 'radio', label: 'Radio', icon: '📻', width: 15, height: 22, color: '#1e293b', category: 'Tactical & Police' },
    { type: 'badge', label: 'Badge', icon: '🪪', width: 18, height: 22, color: '#d4a017', category: 'Tactical & Police' },
    { type: 'megaphone', label: 'Megaphone', icon: '📢', width: 25, height: 18, color: '#dc2626', category: 'Tactical & Police' },
    { type: 'drone', label: 'Drone', icon: '🛸', width: 30, height: 30, color: '#475569', category: 'Tactical & Police' },
    { type: 'searchlight', label: 'Searchlight', icon: '🔦', width: 25, height: 25, color: '#fbbf24', category: 'Tactical & Police' },
  ],
  'Explosives & Arson': [
    { type: 'molotov', label: 'Molotov', icon: '🍾', width: 18, height: 25, color: '#ea580c', category: 'Explosives & Arson' },
    { type: 'grenade', label: 'Grenade', icon: '💣', width: 18, height: 22, color: '#1e293b', category: 'Explosives & Arson' },
    { type: 'ied', label: 'IED', icon: '🧨', width: 25, height: 20, color: '#dc2626', category: 'Explosives & Arson' },
    { type: 'detonator', label: 'Detonator', icon: '🎚️', width: 20, height: 18, color: '#475569', category: 'Explosives & Arson' },
    { type: 'wire', label: 'Wire', icon: '➰', width: 60, height: 6, color: '#dc2626', category: 'Explosives & Arson' },
    { type: 'gunpowder-residue', label: 'GSR', icon: '◌', width: 25, height: 25, color: '#1e293b', category: 'Explosives & Arson' },
    { type: 'shell-fragment', label: 'Shell Fragment', icon: '🔻', width: 15, height: 15, color: '#78716c', category: 'Explosives & Arson' },
    { type: 'arson-pattern', label: 'Arson Pattern', icon: '🔥', width: 60, height: 60, color: '#ea580c', category: 'Explosives & Arson' },
    { type: 'fire-origin', label: 'Fire Origin', icon: '🎯', width: 30, height: 30, color: '#dc2626', category: 'Explosives & Arson' },
    { type: 'soot-mark', label: 'Soot Mark', icon: '⬛', width: 40, height: 30, color: '#1c1917', category: 'Explosives & Arson' },
    { type: 'burn-mark', label: 'Burn Mark', icon: '🟫', width: 35, height: 35, color: '#7c2d12', category: 'Explosives & Arson' },
    { type: 'water-damage', label: 'Water Damage', icon: '💧', width: 50, height: 40, color: '#3b82f6', category: 'Explosives & Arson' },
    { type: 'smoke-stain', label: 'Smoke Stain', icon: '💨', width: 50, height: 40, color: '#475569', category: 'Explosives & Arson' },
    { type: 'broken-glass-pile', label: 'Broken Glass', icon: '🔹', width: 35, height: 25, color: '#67e8f9', category: 'Explosives & Arson' },
  ],
};
